<a href="https://colab.research.google.com/github/Ahowardjr/MSSP6070/blob/main/WeeklyModules/Week%206/Week%206%20Homework%20Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import pandas to work with DataFrames
import pandas as pd

# Upload Student Performance Data.csv from your computer
from google.colab import files
uploaded = files.upload()

Saving Student Performance Data.csv to Student Performance Data (1).csv

In [ ]:
#Read CSV file intoo a dataframe and save as df
df = pd.read_csv("Student Performance Data.csv")

In [ ]:
# Display first 5 rows in the dataframe
display(df.head)))

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [ ]:
# Show the original number of rows and columns
print("Original DataFrame:", df.shape)

Original DataFrame: (1000, 10)

In [ ]:
# Create a lambda function that takes a DataFrame and returns
# a new DataFrame with only students whose math scores are 80 or higher
high_math_scores = lambda df: df.loc[df["math score"] >= 80].copy()

In [ ]:
# Run the lambda function on df and save the new DataFrame
filtered_students = high_math_scores(df)

In [ ]:
# Display the first five rows of the new DataFrame
display(filtered_students.head())

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
2,female,group B,master's degree,standard,90,95,93,278,none,high
6,female,group B,some college,standard,88,95,92,275,completed,high
16,male,group C,high school,standard,88,89,86,263,none,high
34,male,group E,some college,standard,97,87,82,266,none,high
35,male,group E,associate's degree,standard,81,81,79,241,completed,high

In [ ]:
# Show the number of rows and columns in the new DataFrame
print("New DataFrame:", filtered_students.shape)

New DataFrame: (193, 10)

The lambda function selects students who earned a math score of 80 or higher. The new DataFrame shows (193, 10), meaning 193 students met that condition.